version: "3.9"
services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=orider
      - MYSQL_PASSWORD=KyCngL6XPzU=
      - MYSQL_DATABASE=oriderDB
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    healthcheck:
      test: "mysql -u orider -pKyCngL6XPzU= -e 'select 1;'"
      interval: 1s
      timeout: 30s
      retries: 20
      start_period: 10s
    volumes:
      - db:/var/lib/mysql
  app:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    ports:
      - "3000:3000"
    image: t3-app
    environment:
      - NEXTAUTH_SECRET=OhWiIMvslqTT+j4Y0qMEojGTpsMbsIgVF+iIbsT535c=
      - NEXTAUTH_URL=http://localhost:3000
      - JWT_SECRET=40xa8z5BwKrZYITrQYXsexu9PQ==
      - DATABASE_URL=mysql://orider:KyCngL6XPzU=@db:3306/oriderDB
    depends_on:
      db:
        condition : service_healthy
volumes:
  db: {}